export enum TriggerTypeEnum {
	NEW_MY_CLERK=0, 
	APPLY_CLERK_SUCCESS=1, 
	APPLY_CLERK_FAILURE=2, 
	NEW_MY_APPOINTMENT=3, 
	NEW_MY_WORKFLOW=4, 
	PASS_APPLY_CHAIN=5, 
	CHAIN_ALLOT_CLERK=6, 
	CHAIN_PRODUCT_UPDATE=7, 
	CHAIN_PRODUCT_UP=8
}
